# Generated by Django 2.0.1 on 2019-06-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190610_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.FileField(upload_to='pic_folder/'),
        ),
    ]
