# Generated by Django 2.0.1 on 2019-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='first',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='media',
            name='photos',
            field=models.FileField(blank=True, upload_to='something/'),
        ),
    ]
