# Generated by Django 2.0.1 on 2019-06-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190611_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
